version: "3"

services:
  sandwich-app:
    build: .
    restart: 'always'
    ports:
      - 5000:5000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
